import {randomUUID,createHash} from 'node:crypto';
import {mkdirSync,writeFileSync,readFileSync,unlinkSync,existsSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
export function fail(status,message){throw Object.assign(new Error(message),{status});}
export function allowed(user,permission){return user.admin||user.permissoes.includes(permission);}
export function openWorkspace(auth,dir=resolve(dirname(process.env.ER_AUTH_DB||'data/auth.sqlite'),'documents')){
 const db=auth.db;mkdirSync(dir,{recursive:true});db.exec(`CREATE TABLE IF NOT EXISTS tenders(id TEXT PRIMARY KEY,data TEXT NOT NULL,version INTEGER NOT NULL,creator TEXT NOT NULL REFERENCES users(id),created TEXT NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,tender_id TEXT NOT NULL REFERENCES tenders(id),name TEXT NOT NULL,size INTEGER NOT NULL,hash TEXT NOT NULL,creator TEXT NOT NULL,created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS activity(id INTEGER PRIMARY KEY,time TEXT NOT NULL,actor TEXT NOT NULL,name TEXT NOT NULL,action TEXT NOT NULL,tender_id TEXT,details TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,tender_id TEXT NOT NULL REFERENCES tenders(id),actor TEXT NOT NULL,name TEXT NOT NULL,text TEXT NOT NULL,created TEXT NOT NULL);`);
 const event=(u,action,id,details={})=>db.prepare('INSERT INTO activity(time,actor,name,action,tender_id,details) VALUES(?,?,?,?,?,?)').run(new Date().toISOString(),u.id,u.nome,action,id,JSON.stringify(details));
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const out=fn();db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}
 function get(id){const row=db.prepare('SELECT t.*,u.name creator_name FROM tenders t JOIN users u ON u.id=t.creator WHERE t.id=?').get(id);if(!row)fail(404,'Licitação não encontrada.');return {...JSON.parse(row.data),id:row.id,version:row.version,creatorId:row.creator,creatorName:row.creator_name,createdAt:row.created,updatedAt:row.updated};}
 function validate(data){
 if(!data||typeof data!=='object'||Array.isArray(data))fail(400,'Ficha inválida.');
 const textKeys=['titulo','orgao','fonte','modalidade','valor','prazo','uf','urlOrigem','urlPNCP','palavraBusca','motivo','decisao','responsibleId'];const out={};
 for(const k of textKeys){if(data[k]!==undefined){if(typeof data[k]!=='string'||data[k].length>8000)fail(400,'Campo inválido: '+k);out[k]=data[k];}}
 for(const k of ['urlOrigem','urlPNCP'])if(out[k]){try{const u=new URL(out[k]);if(!['http:','https:'].includes(u.protocol))throw Error();}catch{fail(400,'Link inválido.');}}
 for(const k of ['oficial','itensPNCP','manual','analysis'])if(data[k]!==undefined){if(!data[k]||typeof data[k]!=='object'||Array.isArray(data[k]))fail(400,'Campo inválido: '+k);out[k]=data[k];}
 if(out.manual){for(const [key,value] of Object.entries(out.manual))if(key.length>100||typeof value!=='string'||value.length>12000)fail(400,'Campo manual inválido.');}
 if(out.analysis){const a=out.analysis;if(!Array.isArray(a.pricing)||a.pricing.length>100||!Array.isArray(a.tasks)||a.tasks.length>100)fail(400,'Análise inválida.');
 for(const r of a.pricing){if(!r||typeof r.name!=='string'||r.name.length>300||typeof r.disputable!=='boolean')fail(400,'Item de preço inválido.');for(const k of ['quantity','unitPrice','unitCost','taxPercent','indirectCost'])if(r[k]!==null&&(typeof r[k]!=='number'||!Number.isFinite(r[k])||r[k]<0))fail(400,'Valor de preço inválido.');if(r.quantity===0||r.taxPercent>=100)fail(400,'Quantidade ou tributo inválido.');}
 for(const t of a.tasks)if(!t||typeof t.text!=='string'||t.text.length>3000||typeof t.owner!=='string'||!['','Aberta','Em andamento','Concluída'].includes(t.status)||typeof t.due!=='string'||(t.due&&!/^\d{4}-\d{2}-\d{2}$/.test(t.due)))fail(400,'Pendência inválida.');
 if(!a.review||['technical','documentary','operational','financial'].some(k=>!['','Viável','Condicionada','Inviável'].includes(a.review[k]))||!['','Recomendada','Condicionada','Não recomendada'].includes(a.review.conclusion)||typeof a.review.reason!=='string'||a.review.reason.length>12000)fail(400,'Parecer inválido.');
 if(a.review.conclusion==='Recomendada'&&(['technical','documentary','operational','financial'].some(k=>a.review[k]!=='Viável')||!a.review.reason.trim()||a.tasks.some(t=>t.status!=='Concluída')))fail(400,'Recomendação exige quatro viabilidades confirmadas, justificativa e pendências concluídas.');
 }
 if(data.etapa!==undefined){if(!Number.isInteger(data.etapa)||data.etapa<0||data.etapa>4)fail(400,'Etapa inválida.');out.etapa=data.etapa;}
 if(out.decisao&&!['Participar','Não participar','Avaliar'].includes(out.decisao))fail(400,'Decisão inválida.');
 for(const k of ['collaborators','proposalDocuments'])if(data[k]!==undefined){if(!Array.isArray(data[k])||data[k].length>100||data[k].some(v=>typeof v!=='string'))fail(400,'Lista inválida.');out[k]=data[k];}
 if(data.tecnologia!==undefined)out.tecnologia=!!data.tecnologia;
 if(data.coletadoEm!==undefined)out.coletadoEm=String(data.coletadoEm).slice(0,50);
 return out;
 }
 function create(user,input){if(!allowed(user,'Buscar editais'))fail(403,'Sem permissão para iniciar licitações.');const data=validate(input);if(!data.titulo?.trim())fail(400,'Informe um título para a ficha.');const id=typeof input.id==='string'&&input.id.length<=160?input.id:randomUUID();if(db.prepare('SELECT id FROM tenders WHERE id=?').get(id))return get(id);return transaction(()=>{const now=new Date().toISOString();db.prepare('INSERT INTO tenders VALUES(?,?,1,?,?,?)').run(id,JSON.stringify({etapa:0,decisao:'',manual:{},collaborators:[],...data}),user.id,now,now);event(user,'Licitação iniciada',id,{source:data.fonte||''});return get(id);});}
 function patch(user,id,input){return transaction(()=>{const current=get(id);if(input.version!==current.version)fail(409,'Outro colaborador atualizou esta ficha. Reabra para carregar a versão atual.');const changes=validate(input.changes);const keys=Object.keys(changes);for(const k of keys){let perm=['etapa','decisao','motivo'].includes(k)?'Registrar decisões':['proposalDocuments'].includes(k)?'Montar propostas':'Analisar editais';if(!allowed(user,perm))fail(403,'Sem permissão para alterar '+k);}
 for(const uid of [changes.responsibleId,...(changes.collaborators||[])].filter(Boolean))if(!db.prepare('SELECT id FROM users WHERE id=? AND active=1').get(uid))fail(400,'Colaborador inválido.');
 for(const task of changes.analysis?.tasks||[])if(task.owner&&!db.prepare('SELECT id FROM users WHERE id=? AND active=1').get(task.owner))fail(400,'Responsável da pendência inválido.');
 for(const did of changes.proposalDocuments||[])if(!db.prepare('SELECT id FROM documents WHERE id=? AND tender_id=?').get(did,id))fail(400,'Documento de outra licitação.');
 const diff={};for(const k of keys)if(JSON.stringify(current[k])!==JSON.stringify(changes[k]))diff[k]={before:current[k]??null,after:changes[k]};
 if(!Object.keys(diff).length)return current;
 const {version,creatorId,creatorName,createdAt,updatedAt,...saved}=current;db.prepare('UPDATE tenders SET data=?,version=version+1,updated=? WHERE id=?').run(JSON.stringify({...saved,...changes}),new Date().toISOString(),id);event(user,'Ficha alterada',id,diff);return get(id);});}
 function upload(user,id,name,bytes){get(id);if(!allowed(user,'Acessar documentos'))fail(403,'Sem permissão para anexar documentos.');if(!name||name.length>240||!name.toLowerCase().endsWith('.pdf')||bytes.subarray(0,5).toString()!=='%PDF-')fail(400,'Envie um PDF válido.');if(bytes.length>20*1024*1024)fail(413,'Limite: 20 MB por PDF.');const used=db.prepare('SELECT COALESCE(SUM(size),0) n FROM documents').get().n;if(used+bytes.length>Number(process.env.MAX_DOCUMENT_BYTES||400*1024*1024))fail(413,'Limite de documentos do serviço atingido.');const did=randomUUID(),path=resolve(dir,did+'.pdf');writeFileSync(path,bytes,{flag:'wx',mode:0o600});try{return transaction(()=>{const now=new Date().toISOString();const hash=createHash('sha256').update(bytes).digest('hex');db.prepare('INSERT INTO documents VALUES(?,?,?,?,?,?,?)').run(did,id,name,bytes.length,hash,user.id,now);event(user,'PDF anexado',id,{documentId:did,name,size:bytes.length,hash});return {id:did,name,size:bytes.length,hash,created:now};});}catch(e){unlinkSync(path);throw e;}}
 function docs(id){return db.prepare('SELECT id,name,size,hash,created,creator FROM documents WHERE tender_id=? ORDER BY created').all(id);}
 function document(user,id,did){get(id);if(!allowed(user,'Acessar documentos'))fail(403,'Sem permissão para documentos.');const d=db.prepare('SELECT * FROM documents WHERE id=? AND tender_id=?').get(did,id);if(!d)fail(404,'Documento não encontrado nesta licitação.');event(user,'PDF consultado',id,{documentId:did,name:d.name});return {metadata:d,bytes:readFileSync(resolve(dir,did+'.pdf'))};}
 return {dir,db,event,get,create,patch,upload,docs,document,transaction,list:()=>db.prepare('SELECT id FROM tenders ORDER BY updated DESC LIMIT 2000').all().map(r=>get(r.id)),detail(user,id){const t=get(id);event(user,'Ficha aberta',id);return {...t,documents:allowed(user,'Acessar documentos')?docs(id):[],comments:db.prepare('SELECT * FROM comments WHERE tender_id=? ORDER BY created').all(id)};},comment(user,id,text){get(id);if(!allowed(user,'Analisar editais'))fail(403,'Sem permissão para comentar.');if(typeof text!=='string'||!text.trim()||text.length>5000)fail(400,'Comentário inválido.');transaction(()=>{db.prepare('INSERT INTO comments VALUES(?,?,?,?,?,?)').run(randomUUID(),id,user.id,user.nome,text.trim(),new Date().toISOString());event(user,'Comentário registrado',id,{text:text.trim()});});}};
}
