import {officialFields} from '../shared/official-fields.mjs';
import React,{useState} from 'react';
import {SUMMARY_BLOCKS,EXTERNAL_FIELDS,pricingScenario,compareSources} from '../shared/summary-catalog.mjs';
const empty=()=>({pricing:[],tasks:[],review:{technical:'',documentary:'',operational:'',financial:'',conclusion:'',reason:''}});
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function AnalysisPanel({detail,team,manual,setManual,onSave,busy,editable,job}){
 const [a,setA]=useState(()=>detail.analysis||empty()),[discount,setDiscount]=useState(0),[dirty,setDirty]=useState(false),[error,setError]=useState('');
 const change=fn=>{setA(fn);setDirty(true);};const result=pricingScenario(a.pricing,discount);
 function item(index,key,value){change(v=>({...v,pricing:v.pricing.map((r,i)=>i===index?{...r,[key]:value}:r)}));}
 function task(index,key,value){change(v=>({...v,tasks:v.tasks.map((r,i)=>i===index?{...r,[key]:value}:r)}));}
 const report=detail.readingReport||detail.summary?.readingReport;
 const ready=report?.complete!==false&&['technical','documentary','operational','financial'].every(k=>a.review[k]==='Viável')&&a.tasks.every(t=>t.status==='Concluída')&&a.review.reason.trim();
 return <section><h3>Análise completa do edital</h3><p>Abra cada bloco para consultar os campos. Ausência de informação não significa dispensa de exigência. A situação atual exige consulta oficial.</p>{detail.summary&&detail.summary.formatVersion!==20&&<p role="status">Resumo da versão anterior: gere novamente para preencher os oito blocos.</p>}
 {detail.summary?.parts>1&&<p>Resumo consolidado de {detail.summary.parts} partes, com referências de documento e página. Informações diferentes são preservadas para conferência.</p>}
 {report&&<div className="notice" role="status"><b>{report.complete?'Leitura das páginas concluída':'Resumo com leitura parcial — há páginas pendentes'}</b>{detail.summary&&detail.summary.readingReport?.generatedAt!==report.generatedAt&&<p>Esta é a leitura da tentativa mais recente. O resumo exibido abaixo é de uma análise anterior preservada; a nova análise ainda não foi salva.</p>}<p>{report.nativePages} páginas com texto · {report.ocrPages} com OCR · {report.blankPages} em branco · {report.pendingPages} pendentes</p>{report.ocrPages>0&&<p>OCR pode interpretar números e tabelas incorretamente. Confira os trechos no PDF original antes de decidir.</p>}<details><summary>Conferir páginas e métodos de leitura</summary>{report.pages.map(p=><p key={p.documentId+':'+p.page}>{p.name} · página {p.page} · {({native:'Texto do PDF',ocr:'OCR',blank:'Em branco',pending:'Pendente'})[p.status]}{p.confidence!==undefined?' · confiança OCR '+p.confidence+'%':''}{p.reason?' · '+p.reason:''}</p>)}</details></div>}
 {SUMMARY_BLOCKS.map((b,index)=><details className="analysis-block" key={b.id}><summary><b>{index+1}. {b.title}</b></summary>{b.fields.map(f=>{const portal=(detail.officialCollection?.fields||(detail.fonte==='PNCP'?officialFields(detail.oficial||{},[],detail.coletadoEm||detail.createdAt):[])).find(x=>x.id===f.id);const extracted=detail.summary?.formatVersion===20?detail.summary.fields.find(x=>x.label===f.id):null;const comparison=compareSources(f.id,portal?.value,extracted?.value);return <section className="analysis-field" key={f.id}><h4>{f.label}</h4>{portal?.value&&<div className="notice"><b>Fonte: PNCP</b><p style={{whiteSpace:'pre-wrap'}}>{portal.value}</p><small>{portal.key} · consultado em {new Date(portal.consultedAt).toLocaleString('pt-BR')}</small>{extracted?.value&&<p><b>{comparison.status}:</b> {comparison.message} Nenhum valor é substituído automaticamente.</p>}</div>}<small>{EXTERNAL_FIELDS.has(f.id)?'Dados da empresa / confirmação externa':'Extração dos documentos da licitação'}</small><p style={{whiteSpace:'pre-wrap'}}>{extracted?.value||(EXTERNAL_FIELDS.has(f.id)?'Depende de dados ou confirmação da equipe.':!detail.summary?(['fila','processando'].includes(job?.status)?'Análise em andamento — informação ainda não extraída.':job?.status==='falhou'?'Análise falhou — consulte a mensagem no início da ficha.':'Ainda não analisado — nenhum resumo foi gerado.'):detail.summary.formatVersion!==20?'Resumo anterior — gere novamente para este formato.':extracted?.note||'Não localizado nos documentos analisados.')}</p>{extracted?.note&&<small>{extracted.note}</small>}{extracted?.evidence?.map((e,i)=><blockquote key={i} className="summary-evidence">{detail.summary.documents.find(d=>d.id===e.documentId)?.name} · página {e.page}<br/>“{e.quote}”</blockquote>)}<label>Complemento da equipe<textarea disabled={!editable||busy} value={manual[f.id]||''} onChange={e=>setManual(v=>({...v,[f.id]:e.target.value}))} placeholder="Deixe vazio se não houver informação confirmada."/></label></section>;})}</details>)}
 {Object.keys(manual).some(k=>!/^b\d+_\d+$/.test(k))&&<details><summary>Complementos anteriores preservados</summary>{Object.entries(manual).filter(([k])=>!/^b\d+_\d+$/.test(k)).map(([k,v])=><label key={k}>{k}<textarea disabled={!editable} value={v} onChange={e=>setManual(m=>({...m,[k]:e.target.value}))}/></label>)}</details>}<h3>Custos e simulação de descontos</h3><p>Preencha cotações reais. O preço unitário é o cenário de venda escolhido pela equipe; não é extraído automaticamente do orçamento. Custos indiretos são o total alocado a cada linha. Valores reembolsáveis também precisam de custo e tratamento tributário confirmado.</p>
 {a.pricing.map((r,i)=><fieldset key={i}><legend>Item {i+1}</legend><label>Descrição<input disabled={!editable} value={r.name} onChange={e=>item(i,'name',e.target.value)}/></label><div className="analysis-numbers">{[['quantity','Quantidade'],['unitPrice','Preço unitário de venda (R$)'],['unitCost','Custo unitário cotado (R$)'],['taxPercent','Tributos sobre receita (%)'],['indirectCost','Custos indiretos totais (R$)']].map(([k,label])=><label key={k}>{label}<input type="number" min="0" step="any" disabled={!editable} value={r[k]??''} onChange={e=>item(i,k,e.target.value===''?null:Number(e.target.value))}/></label>)}</div><label><input type="checkbox" disabled={!editable} checked={r.disputable} onChange={e=>item(i,'disputable',e.target.checked)}/> Aplicar desconto de disputa a este item</label><button disabled={!editable} onClick={()=>change(v=>({...v,pricing:v.pricing.filter((_,n)=>n!==i)}))}>Remover linha</button></fieldset>)}
 <button disabled={!editable||a.pricing.length>=100} onClick={()=>change(v=>({...v,pricing:[...v.pricing,{name:'',quantity:null,unitPrice:null,unitCost:null,taxPercent:null,indirectCost:null,disputable:true}]}))}>Adicionar item cotado</button><label>Desconto simulado (%)<input type="number" min="0" max="99.99" step="0.1" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label>
 {result?<><p>Receita: <b>{money(result.revenue)}</b> · Custos: {money(result.cost)} · Tributos: {money(result.tax)} · Resultado: <b>{money(result.profit)}</b> · Margem: {result.margin===null?'Indefinida':result.margin.toFixed(2)+'%'}</p><p>Ponto de equilíbrio global: {money(result.breakEven)}. Não inclui custos que não tenham sido informados; não é um preço mínimo certificado.</p><div className="table-scroll"><table><thead><tr><th>Item</th><th>Receita</th><th>Resultado</th><th>Equilíbrio</th></tr></thead><tbody>{result.items.map((r,i)=><tr key={i}><td>{r.name||'Sem descrição'}</td><td>{money(r.revenue)}</td><td>{money(r.profit)}</td><td>{money(r.breakEven)}</td></tr>)}</tbody></table></div></>:<p>Cálculo pendente: preencha todas as quantidades, preços, custos e tributos. Zero deve ser informado explicitamente quando confirmado.</p>}
 <h3>Pendências e plano de ação</h3>{a.tasks.map((t,i)=><fieldset key={i}><label>Pendência / providência / referência<textarea disabled={!editable} value={t.text} onChange={e=>task(i,'text',e.target.value)}/></label><label>Responsável<select disabled={!editable} value={t.owner} onChange={e=>task(i,'owner',e.target.value)}><option value="">Não atribuído</option>{team.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select></label><label>Prazo confirmado<input type="date" disabled={!editable} value={t.due} onChange={e=>task(i,'due',e.target.value)}/></label><label>Status<select disabled={!editable} value={t.status} onChange={e=>task(i,'status',e.target.value)}>{['Aberta','Em andamento','Concluída'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={!editable} onClick={()=>change(v=>({...v,tasks:v.tasks.filter((_,n)=>n!==i)}))}>Remover pendência</button></fieldset>)}<button disabled={!editable||a.tasks.length>=100} onClick={()=>change(v=>({...v,tasks:[...v.tasks,{text:'',owner:'',due:'',status:'Aberta'}]}))}>Adicionar pendência</button>
 <h3>Parecer revisado pela equipe</h3>{[['technical','Viabilidade técnica'],['documentary','Viabilidade documental'],['operational','Viabilidade operacional'],['financial','Viabilidade financeira']].map(([k,label])=><label key={k}>{label}<select disabled={!editable} value={a.review[k]} onChange={e=>change(v=>({...v,review:{...v.review,[k]:e.target.value,conclusion:v.review.conclusion==='Recomendada'?'Condicionada':v.review.conclusion}}))}><option value="">Não avaliada</option>{['Viável','Condicionada','Inviável'].map(s=><option key={s}>{s}</option>)}</select></label>)}<label>Justificativa<textarea disabled={!editable} value={a.review.reason} onChange={e=>change(v=>({...v,review:{...v.review,reason:e.target.value}}))}/></label><label>Conclusão<select disabled={!editable} value={a.review.conclusion} onChange={e=>change(v=>({...v,review:{...v.review,conclusion:e.target.value}}))}><option value="">Condicionada à validação — sem parecer final</option><option disabled={!ready}>Recomendada</option><option>Condicionada</option><option>Não recomendada</option></select></label><p>Recomendação exige as quatro viabilidades confirmadas, justificativa, pendências concluídas e nenhuma página com leitura pendente. O parecer não muda automaticamente a decisão de participar.</p>{dirty&&<p role="status">Há alterações nesta análise ainda não salvas.</p>}<button className="primary" disabled={busy||!editable} onClick={()=>{setError('');onSave({manual,analysis:a}).then(()=>setDirty(false)).catch(e=>setError(e.message));}}>Salvar análise e complementos</button>
 {error&&<p role="alert">{error}</p>}<style>{`.analysis-block{border:1px solid #dbe4f0;border-radius:8px;margin:12px 0;padding:14px}.analysis-block>summary{cursor:pointer;color:#061d68}.analysis-field{padding:12px 0;border-bottom:1px solid #e5ebf3}.analysis-numbers{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.shared-modal fieldset{border:1px solid #dbe4f0;border-radius:8px;margin:14px 0;padding:14px}`}</style></section>;
}
